"""removing the session_id from staff_attendence and student_attendence table

Revision ID: d99e7d868e01
Revises: 1b2db026cbf6
Create Date: 2024-05-14 11:33:03.586798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99e7d868e01'
down_revision = '1b2db026cbf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_attendence', schema=None) as batch_op:
        batch_op.drop_constraint('session_id', type_='foreignkey')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('student_attendence', schema=None) as batch_op:
        batch_op.drop_constraint('session_id', type_='foreignkey')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attendence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('session_id', 'session_year', ['session_id'], ['id'])

    with op.batch_alter_table('staff_attendence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('session_id', 'session_year', ['session_id'], ['id'])

    # ### end Alembic commands ###
